upload_image:
    documents_dir: 'E:\Mes Projets\cv\back_cv/public/uploads/documents'
    videos_dir: 'E:\Mes Projets\cv\back_cv/public/uploads/videos'
    images_dir: 'E:\Mes Projets\cv\back_cv/public/uploads/images'
